apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: auvmp
  labels:
    app: web-auvmp
  name: deployment-web-auvmp
  annotations:
    version: 23.07.19
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-auvmp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: web-auvmp
    spec:
      containers:
      - image: localhost:32000/web-auvmp-frontend:23.07.19
        name: web-auvmp-frontend-image
        imagePullPolicy: Always
        ports:
        - containerPort: 80
